name: Build & Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo-app:latest .

      - name: Save Docker image
        run: docker save demo-app:latest | gzip > demo-app.tar.gz

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: demo-app.tar.gz
          target: /home/ubuntu/

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load docker image
            gunzip -c /home/ubuntu/demo-app.tar.gz | docker load

            # Stop old container
            docker stop demo-app || true
            docker rm demo-app || true

            # Run container
            docker run -d \
              --name demo-app \
              --restart unless-stopped \
              -p 3000:3000 \
              demo-app:latest

            # Remove tar file
            rm -f /home/ubuntu/demo-app.tar.gz

            # Show running containers
            docker ps